### ISSUE TITLE
Hello, could you please provide the split files for training, dev, and test splits in Table 2? 

### ISSUE THREAD

**Issue by RedamancyAY** [csun22/Synthetic-Voice-Detection-Vocoder-Artifacts#1]
<center><img src="https://raw.githubusercontent.com/RedamancyAY/CloudImage/main/imgCleanShot 2023-06-30 at 10.09.27@2x.png" width="400" alt="CleanShot 2023-06-30 at 10.09.27@2x"/></center>

**Comment by csun22** [comment]
Sure, not a problem. However, because of data privacy, we will only update the LibriSeVoc dataset's split files for training, dev, and testing.

**Comment by csun22** [comment]
The txt file has been updated.
