### ISSUE TITLE
Is there any other way to get the dataset?

### ISSUE THREAD

**Issue by KevinBaylor** [csun22/Synthetic-Voice-Detection-Vocoder-Artifacts#13]
Thanks for open-sourcing the dataset. 

I've tried many times to download the zip from the given link, but the connection keeps dropping.

I'd like to know is there any other way available, like Baiduyun or Aliyun?

**Comment by csun22** [comment]
Sorry for the inconvenience. Since we do not have Baiduyun and Aliyun accounts, Google Drive is the only way to download it.
