### ISSUE TITLE
Trained vocoders

### ISSUE THREAD

**Issue by Ashigarg123** [csun22/Synthetic-Voice-Detection-Vocoder-Artifacts#14]
Hello,

Thank you for the great work! Can you please share pre-trained vocoder checkpoints that you might have trained to synthesize?

Thanks

**Comment by SwenHou** [comment]
Hi,

Thanks for your feedback. Because some hyper parameter modifications, It’s hard to use our pre-trained vocoders directly. It is recommended to train your own vocoders to better suit your needs.

**Comment by Ashigarg123** [comment]
No problem! Is it possible to just share what was the training data for vocoders?
