### ISSUE TITLE
Request for Training and Evaluation Code

### ISSUE THREAD

**Issue by chandlerbing65nm** [csun22/Synthetic-Voice-Detection-Vocoder-Artifacts#2]
I'm interested in your CVPR paper and would like to replicate your experiments. Could you please upload the training and evaluation code?

**Comment by csun22** [comment]
There is a hold on the training and evaluation code now. It will be released in early 2024. I appreciate your interest.

**Comment by nabeelxy** [comment]
Thank you for your work. Any update on releasing the training and testing codes, and the pertained models?

**Comment by csun22** [comment]
The code will be published in three weeks.

**Comment by mamarasulovs** [comment]
> The code will be published in three weeks.

any update?

**Comment by csun22** [comment]
The code has been uploaded. Please let me know if you have any questions.
Thank you!

On Sun, Mar 10, 2024 at 12:04 PM sardor-m ***@***.***> wrote:

> The code will be published in three weeks.
>
> any update?
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcsun22%2FSynthetic-Voice-Detection-Vocoder-Artifacts%2Fissues%2F2%23issuecomment-1987279700&data=05%7C02%7Ccsun22%40g-mail.buffalo.edu%7Ce68b8f90f31a4252605808dc411bd3be%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C638456834970008035%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=EfkT04Fo6ruTWTaw83cyMyzj%2B6neWM%2B56NFJC4JKYsA%3D&reserved=0>,
> or unsubscribe
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHR44WQYY6Y4U4D2FI7K6STYXSACNAVCNFSM6AAAAAA5FXQYTGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOBXGI3TSNZQGA&data=05%7C02%7Ccsun22%40g-mail.buffalo.edu%7Ce68b8f90f31a4252605808dc411bd3be%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C638456834970008035%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=kj6O7%2FASKnPoewaWkjLY21qn18oKflb%2FaUJdjrg5fCc%3D&reserved=0>
> .
> You are receiving this because you commented.Message ID:
> <csun22/Synthetic-Voice-Detection-Vocoder-Artifacts/issues/2/1987279700@
> github.com>
>


-- 
Chengzhe Sun
Laboratory Manager & Research Assistant
UB Media Forensics Lab (UB MDFL)
Department of Computer Science & Engineering 301A Davis Hall (716) 645-4768
