### ISSUE TITLE
full script

### ISSUE THREAD

**Issue by mamarasulovs** [csun22/Synthetic-Voice-Detection-Vocoder-Artifacts#5]
Thank you for the awesome project. Could you provide a full script to me (mamarasulovsardor@gmail.com), I would like to do some experiment.

Thanks

**Comment by ghost** [comment]
If possible, I am requesting full script too (dmitryblum@tutanota.com)
Thank you very much)

**Comment by BlazJurisic** [comment]
also, to me too please (jurisic.blaz@gmail.com)

**Comment by csun22** [comment]
Hi all,
I appreciate your interest in my paper. The training code will be published soon after the hold release.
