### ISSUE TITLE
Name of vocoders training datasets

### ISSUE THREAD

**Issue by Hactogeek** [csun22/Synthetic-Voice-Detection-Vocoder-Artifacts#6]
Hello,

Thank you for sharing this dataset.

Would it be possible to have more information on the generation of audios? In particular, the names of the vocoders training datasets used.

Thank you.

Tony

**Comment by csun22** [comment]
Hi Tony,
Those are included in our paper. https://openaccess.thecvf.com/content/CVPR2023W/WMF/html/Sun_AI-Synthesized_Voice_Detection_Using_Neural_Vocoder_Artifacts_CVPRW_2023_paper.html
