### ISSUE TITLE
Release of pre-trained models

### ISSUE THREAD

**Issue by ajinkyakulkarni14** [csun22/Synthetic-Voice-Detection-Vocoder-Artifacts#7]
Hello 
Thanks for dataset, can you release pre-trained models for vocoder detection system?

Regards
Ajinkya

**Comment by mittalgovind** [comment]
Was the pre-trained model already released? I seem to not able to find it.

**Comment by csun22** [comment]
Yes, it is under core scripts, and we are still uploading detailed
instructions and files.

On Mon, Jun 3, 2024 at 5:34 PM Govind Mittal ***@***.***>
wrote:

> Was the pre-trained model already released? I seem to not able to find it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcsun22%2FSynthetic-Voice-Detection-Vocoder-Artifacts%2Fissues%2F7%23issuecomment-2146164287&data=05%7C02%7Ccsun22%40g-mail.buffalo.edu%7C563f4692a513491ac3f708dc8414fb36%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C638530472860169786%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=vjRsE4X5AtTvqUyxNzr9JaLQgNesx9BclkNUvveFWG8%3D&reserved=0>,
> or unsubscribe
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHR44WWMJ4KROK2RM5ON7RLZFTOPFAVCNFSM6AAAAABFVGRIAGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNBWGE3DIMRYG4&data=05%7C02%7Ccsun22%40g-mail.buffalo.edu%7C563f4692a513491ac3f708dc8414fb36%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C638530472860169786%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=P5hRTFYrjOudfXSNjygu3jvwyKCeJ7b3mv5U1ylblQc%3D&reserved=0>
> .
> You are receiving this because you modified the open/close state.Message
> ID:
> <csun22/Synthetic-Voice-Detection-Vocoder-Artifacts/issues/7/2146164287@
> github.com>
>


-- 
Chengzhe Sun
Laboratory Manager & Research Assistant
UB Media Forensics Lab (UB MDFL)
Department of Computer Science & Engineering 301A Davis Hall (716) 645-4768
