### ISSUE TITLE
Benckmark and experiment for WavLM in AntiSpoofing

### ISSUE THREAD

**Issue by v-nhandt21** [csun22/Synthetic-Voice-Detection-Vocoder-Artifacts#8]
I found your paper here: https://arxiv.org/pdf/2304.13085 

Thanks for your contribution!

Can you provide more detail description or sample source code for WavLM in your paper?

I have tried to reproduce it but the result seen not to be potential!

P/S: Do you know which is the best EER performing on ASVSpoof2019?

**Comment by csun22** [comment]
Hi 
We use STOA WavLM https://huggingface.co/docs/transformers/en/model_doc/wavlm
With retraining on our LibriSevoc dataset. 
For your question, please check the ASVspoof website: https://competitions.codalab.org/competitions/32345.
Please let me know if you have any other questions.
