### ISSUE TITLE
Pre-train model release

### ISSUE THREAD

**Issue by steven84418** [csun22/Synthetic-Voice-Detection-Vocoder-Artifacts#9]
Hi, 
Thanks for all the great work. You said you will put pre-train model in core_script folder in reply of another  issue. But I can't find it

**Comment by csun22** [comment]
Hi Steven，
Do you mean our pre-train model?

**Comment by steven84418** [comment]
The model you used for the result

**Comment by csun22** [comment]
Yes. There are two ways you can do it. 
1.python eval.py --input_path /your/path/to/sample.wav --model_path /your/path/to/your_model.pth the eval.py file is provided.
2. https://zinc.cse.buffalo.edu/ubmdfl/deep-o-meter/landing_page 
using this platform to test out.

**Comment by Rizwanali324** [comment]
can u upload weights here instead of on website as open source

**Comment by jreivilo** [comment]
Hey

Would be great indeed to have the weight of the trained model in the repo :)

Thanks

**Comment by csun22** [comment]
Thank you all. The weight of the trained model has been uploaded to the readme with a Google Drive link. 
https://drive.google.com/file/d/1TWdsCFKP2luAfhpB91N9X4z1gsJMvvhI/view?usp=drive_link
Please let me know if you have any questions.

**Comment by Rizwanali324** [comment]
> Thank you all. The weight of the trained model has been uploaded to the readme with a Google Drive link. https://drive.google.com/file/d/1TWdsCFKP2luAfhpB91N9X4z1gsJMvvhI/view?usp=drive_link Please let me know if you have any questions.

any instruction for to use it for custom as I'm working on project with this dataset

**Comment by Rizwanali324** [comment]
Also, can you share other evaluation matrices?
we are trying to deploy it on real time so we need to know inference speed and percision

**Comment by SwenHou** [comment]
> > Thank you all. The weight of the trained model has been uploaded to the readme with a Google Drive link. https://drive.google.com/file/d/1TWdsCFKP2luAfhpB91N9X4z1gsJMvvhI/view?usp=drive_link Please let me know if you have any questions.
> 
> any instruction for to use it for custom as I'm working on project with this dataset

To use the pretrained weight, you can run 'python eval.py --input_path /your/path/to/sample.wav --model_path /your/path/to/your_model.pth' 

you can also check the code in eval.py to make any modifications according to your custom requirements

**Comment by SwenHou** [comment]
> Also, can you share other evaluation matrices? we are trying to deploy it on real time so we need to know inference speed and percision

You can check our paper for any evaluation metrices, the inference speed is fast enough for real time detection, inference time should be less than 1s for about 10s of speech, after loading the weight.

**Comment by Rizwanali324** [comment]
> > Also, can you share other evaluation matrices? we are trying to deploy it on real time so we need to know inference speed and percision
> 
> You can check our paper for any evaluation metrices, the inference speed is fast enough for real time detection, inference time should be less than 1s for about 10s of speech, after loading the weight.

there's  is no such matrix just reduce error rate
